# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0003_auto_20171010_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
