# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0007_auto_20171025_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='session',
            name='startTime',
        ),
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='session',
            name='time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
