# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0008_auto_20171031_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
