# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0009_tutor_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='time',
        ),
        migrations.AddField(
            model_name='session',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='session',
            name='startTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
