# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0010_auto_20171105_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
