# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0011_auto_20171105_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
