# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0014_session_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoria.Student'),
        ),
    ]
