# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0016_auto_20171110_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminwallet',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
