# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0017_adminwallet_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminWallet',
        ),
    ]
