# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0021_transaction_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('viewed_stu', models.BooleanField(default=False)),
                ('viewed_tut', models.BooleanField(default=False)),
                ('now', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('date', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoria.Student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoria.Tutor')),
            ],
        ),
    ]
