# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0022_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='forSession',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
