# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0025_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='tutor',
            name='course',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='tutor',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tutor',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
