# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0026_auto_20171120_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phoneNumber',
            field=models.DecimalField(decimal_places=0, default=99999999, max_digits=10),
        ),
        migrations.AddField(
            model_name='tutor',
            name='phoneNumber',
            field=models.DecimalField(decimal_places=0, default=99999999, max_digits=10),
        ),
    ]
