# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0027_auto_20171120_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='avatar',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='tutor',
            name='isHidden',
            field=models.BooleanField(default=False),
        ),
    ]
