# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0028_auto_20171121_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
            ],
        ),
    ]
