# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0028_auto_20171121_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='phoneNumber',
            field=models.IntegerField(default=99999999),
        ),
    ]
