# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0030_remove_tutor_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='avatar',
            field=models.FileField(default='http://s3.amazonaws.com/37assets/svn/765-default-avatar.png', upload_to=''),
        ),
    ]
