# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0031_auto_20171121_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='phoneNumber',
            field=models.IntegerField(default=99999999),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
