# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0028_auto_20171121_0124'),
        ('tutoria', '0032_auto_20171121_1317'),
    ]

    operations = [
    ]
