# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0034_tutor_tags'),
        ('tutoria', '0030_auto_20171122_1057'),
    ]

    operations = [
    ]
