# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0035_merge_20171122_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='session',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='tutoria.Session'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='hasRating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutor',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
