# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0036_auto_20171122_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='avatar',
            field=models.FileField(default='anonymous.png', upload_to=''),
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='course',
        ),
        migrations.AddField(
            model_name='tutor',
            name='course',
            field=models.ManyToManyField(to='tutoria.Course'),
        ),
    ]
