# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0037_auto_20171123_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='subject',
        ),
    ]
