# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0038_remove_tutor_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoria.Student'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoria.Tutor'),
        ),
    ]
