# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0039_auto_20171123_1804'),
        ('tutoria', '0039_auto_20171123_1648'),
    ]

    operations = [
    ]
