# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0039_auto_20171123_1459'),
        ('tutoria', '0039_auto_20171123_1648'),
    ]

    operations = [
    ]
