# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0040_merge_20171123_1746'),
        ('tutoria', '0040_merge_20171123_1811'),
    ]

    operations = [
    ]
