# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0042_notification_forreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='student',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='viewed_stu',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='viewed_tut',
        ),
    ]
