# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0044_auto_20171124_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoria.Session'),
        ),
    ]
