# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0042_auto_20171124_1647'),
        ('tutoria', '0046_auto_20171124_1734'),
    ]

    operations = [
    ]
