# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0047_merge_20171124_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='booked_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
