# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0048_transaction_booked_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytutorswallet',
            old_name='amount',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='now',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='end_time',
            new_name='session_end_time',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='start_time',
            new_name='session_start_time',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='viewed_stu',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='viewed_tut',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='discount',
        ),
    ]
